// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package capture

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type connectPidInfo struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

// loadConnect returns the embedded CollectionSpec for connect.
func loadConnect() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connect: %w", err)
	}

	return spec, err
}

// loadConnectObjects loads connect and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connectObjects
//	*connectPrograms
//	*connectMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnectObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnect()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connectSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectSpecs struct {
	connectProgramSpecs
	connectMapSpecs
	connectVariableSpecs
}

// connectProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectProgramSpecs struct {
	InetCskAccept *ebpf.ProgramSpec `ebpf:"inet_csk_accept"`
	TcpClose      *ebpf.ProgramSpec `ebpf:"tcp_close"`
	TcpConnect    *ebpf.ProgramSpec `ebpf:"tcp_connect"`
}

// connectMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	PidByInode *ebpf.MapSpec `ebpf:"pid_by_inode"`
}

// connectVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectVariableSpecs struct {
}

// connectObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectObjects struct {
	connectPrograms
	connectMaps
	connectVariables
}

func (o *connectObjects) Close() error {
	return _ConnectClose(
		&o.connectPrograms,
		&o.connectMaps,
	)
}

// connectMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	PidByInode *ebpf.Map `ebpf:"pid_by_inode"`
}

func (m *connectMaps) Close() error {
	return _ConnectClose(
		m.Events,
		m.PidByInode,
	)
}

// connectVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectVariables struct {
}

// connectPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnectObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectPrograms struct {
	InetCskAccept *ebpf.Program `ebpf:"inet_csk_accept"`
	TcpClose      *ebpf.Program `ebpf:"tcp_close"`
	TcpConnect    *ebpf.Program `ebpf:"tcp_connect"`
}

func (p *connectPrograms) Close() error {
	return _ConnectClose(
		p.InetCskAccept,
		p.TcpClose,
		p.TcpConnect,
	)
}

func _ConnectClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connect_bpfel.o
var _ConnectBytes []byte
